# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [3]:
print(np.version.version)

2.2.5


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [11]:
# Way 1 --> Using a tuple (2, 3, 5) as an argument
a = np.random.random((2, 3, 5))

print(a)

print("Way 1 result.")

# Way 2 --> Using dimensions directly instead of a tuple to define the array. 
a = np.random.rand(2, 3, 5)

print(a)

print("Way 2 result.")

# Way 3 --> This is similar to way 1, but the first two places of the argument are to set the min and maax value of the range from which we should generate the random values. 
a = np.random.uniform(5, 10, (2, 3, 5))

print(a)

print("Way 3 result.")


#For the next exercise, let's use the first iteration of a:

a = np.random.random((2, 3, 5))

[[[0.00981632 0.10487195 0.75172023 0.24717833 0.1757527 ]
  [0.28466374 0.11573415 0.02898033 0.19788668 0.55923292]
  [0.3909844  0.2197333  0.93232603 0.58334253 0.51506052]]

 [[0.77208879 0.1081357  0.42335421 0.41416298 0.02054184]
  [0.97612701 0.68891587 0.46166182 0.87802931 0.1344402 ]
  [0.12471473 0.971848   0.16558616 0.59028948 0.17461716]]]
Way 1 result.
[[[0.10815675 0.20357791 0.04645035 0.74097967 0.50536846]
  [0.87056147 0.05694009 0.56844548 0.48487816 0.8391152 ]
  [0.11785172 0.79252638 0.84433558 0.37761322 0.35078954]]

 [[0.58563343 0.45460649 0.60805108 0.86105639 0.35747511]
  [0.08480654 0.66506703 0.47416759 0.48257034 0.41581101]
  [0.3278739  0.01095876 0.42482839 0.51821374 0.17643662]]]
Way 2 result.
[[[9.57002042 6.27715117 5.84649964 5.75971897 5.29035103]
  [8.15113081 6.43689239 9.15706219 9.94508772 5.74917366]
  [6.0035414  5.28826462 9.54471226 8.92331808 5.92352057]]

 [[7.69727074 7.1177014  6.6091268  9.87589836 9.11025159]
  [9.39751299 8.31


### 4. Print a.


In [12]:
print(a)

[[[0.04351799 0.71964368 0.98239922 0.80435276 0.6917323 ]
  [0.8062494  0.10107773 0.10673246 0.04102788 0.47390678]
  [0.00869559 0.17332658 0.81141575 0.76646175 0.82315202]]

 [[0.25904348 0.80230673 0.37430907 0.86166923 0.33292779]
  [0.80761588 0.04442697 0.72960752 0.22502103 0.01414849]
  [0.36082474 0.82508008 0.19013151 0.81064563 0.48328153]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [18]:
b = np.ones((5, 2, 3))


### 6. Print b.


In [19]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [20]:
a.size == b.size


True


### 8. Are you able to add a and b? Why or why not?


In [24]:
def add_arrays(a, b):
    try:
        result = np.add(a, b)

        return result
    
    except ValueError:
        print("We cannot add them, as they don't have the same shape. ")

add_arrays(a, b)


We cannot add them, as they don't have the same shape. 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [60]:
b = b.ravel()

b = b.reshape(5, 3, 2)

c = np.transpose(b)

c.shape



(2, 3, 5)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
d = np.add(a, c)

#Now it works, because after reshaping and transposing b, the shape is 2x3x5, which matches with the one from a. 



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [64]:

print(a)

print("End of a")

print(d)

print("End of d")

#The relation between the values of a and d is that a values are exactly the same as d values, but substracting 1. This makes sense, as c was a "ones" array, so the sum will add 1 to all the values from array a. 

[[[0.04351799 0.71964368 0.98239922 0.80435276 0.6917323 ]
  [0.8062494  0.10107773 0.10673246 0.04102788 0.47390678]
  [0.00869559 0.17332658 0.81141575 0.76646175 0.82315202]]

 [[0.25904348 0.80230673 0.37430907 0.86166923 0.33292779]
  [0.80761588 0.04442697 0.72960752 0.22502103 0.01414849]
  [0.36082474 0.82508008 0.19013151 0.81064563 0.48328153]]]
End of a
[[[1.04351799 1.71964368 1.98239922 1.80435276 1.6917323 ]
  [1.8062494  1.10107773 1.10673246 1.04102788 1.47390678]
  [1.00869559 1.17332658 1.81141575 1.76646175 1.82315202]]

 [[1.25904348 1.80230673 1.37430907 1.86166923 1.33292779]
  [1.80761588 1.04442697 1.72960752 1.22502103 1.01414849]
  [1.36082474 1.82508008 1.19013151 1.81064563 1.48328153]]]
End of d



### 12. Multiply a and c. Assign the result to e.


In [65]:
e = np.multiply(a, c)



### 13. Does e equal to a? Why or why not?


In [68]:
np.array_equal(e, a)

# e equals a, as when mulyipying a by c, as all the values in c are 1, the result of the multiplication will return the exact same values that were originally in array a. That is why, all the values from e (resulting from a * c multiplication) will be the same as the values from a.


True



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [76]:
d_max = d.max()

print(d_max)

d_min = d.min()

print(d_min)

d_mean = d.mean()

print(d_mean)


1.9823992239262962
1.0086955911402782
1.4824910524208432



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [77]:
f = np.empty((2, 3, 5))

f

array([[[1.04351799, 1.71964368, 1.98239922, 1.80435276, 1.6917323 ],
        [1.8062494 , 1.10107773, 1.10673246, 1.04102788, 1.47390678],
        [1.00869559, 1.17332658, 1.81141575, 1.76646175, 1.82315202]],

       [[1.25904348, 1.80230673, 1.37430907, 1.86166923, 1.33292779],
        [1.80761588, 1.04442697, 1.72960752, 1.22502103, 1.01414849],
        [1.36082474, 1.82508008, 1.19013151, 1.81064563, 1.48328153]]])




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [91]:
d = d.ravel()

f = f.ravel()

i = 0

for element in d:
    if d[i] == d_max:
        f[i] = 100
        i += 1
    elif d_mean < d[i] < d_max:
        f[i] = 75
        i += 1
    elif d[i] == d_mean:
        f[i] = 50
        i += 1
    elif d_mean > d[i] > d_min:
        f[i] = 25
        i += 1
    elif d[i] == d_min:
        f[i] = 0
        i += 1

d = d.reshape(2, 3, 5)

f = f.reshape(2, 3, 5)

f = f.astype(int)

f

array([[[ 25,  75, 100,  75,  75],
        [ 75,  25,  25,  25,  25],
        [  0,  25,  75,  75,  75]],

       [[ 25,  75,  25,  75,  25],
        [ 75,  25,  75,  25,  25],
        [ 25,  75,  25,  75,  75]]])





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [92]:
print(d)

print("End of array d.")

print(f)

print("End of array f.")


[[[1.04351799 1.71964368 1.98239922 1.80435276 1.6917323 ]
  [1.8062494  1.10107773 1.10673246 1.04102788 1.47390678]
  [1.00869559 1.17332658 1.81141575 1.76646175 1.82315202]]

 [[1.25904348 1.80230673 1.37430907 1.86166923 1.33292779]
  [1.80761588 1.04442697 1.72960752 1.22502103 1.01414849]
  [1.36082474 1.82508008 1.19013151 1.81064563 1.48328153]]]
End of array d.
[[[ 25  75 100  75  75]
  [ 75  25  25  25  25]
  [  0  25  75  75  75]]

 [[ 25  75  25  75  25]
  [ 75  25  75  25  25]
  [ 25  75  25  75  75]]]
End of array f.


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [96]:
d = d.ravel()

f = f.ravel()

i = 0

f = f.astype(str)

for element in d:
    if d[i] == d_max:
        f[i] = "E"
        i += 1
    elif d_mean < d[i] < d_max:
        f[i] = "D"
        i += 1
    elif d[i] == d_mean:
        f[i] = "C"
        i += 1
    elif d_mean > d[i] > d_min:
        f[i] = "B"
        i += 1
    elif d[i] == d_min:
        f[i] = "A"
        i += 1

d = d.reshape(2, 3, 5)

f = f.reshape(2, 3, 5)

f

array([[['B', 'D', 'E', 'D', 'D'],
        ['D', 'B', 'B', 'B', 'B'],
        ['A', 'B', 'D', 'D', 'D']],

       [['B', 'D', 'B', 'D', 'B'],
        ['D', 'B', 'D', 'B', 'B'],
        ['B', 'D', 'B', 'D', 'D']]], dtype='<U21')